### ISSUE TITLE
error: incompatible types: NativeAd cannot be converted to UnifiedNativeAd

### ISSUE THREAD

**Issue by veby91** [googleads/googleads-mobile-android-native-templates#18] opened 2021-03-07 22:13 UTC
I use latest sdk version 19.7.0 and i got this error when build:

error: incompatible types: NativeAd cannot be converted to UnifiedNativeAd

**Comment by msiejak** [comment] 2021-03-11 19:26
I resolved this issue in resolved in #17

**Comment by ashprog** [comment] 2021-04-05 18:16
Issue not resolved yet.

**Comment by FonzTech** [comment] 2021-04-05 20:18
> Issue not resolved yet.

Follow these steps to clone the #17 :
`git clone https://github.com/googleads/googleads-mobile-android-native-templates.git
cd googleads-mobile-android-native-templates
git remote add msiejak https://github.com/googleads/googleads-mobile-android-native-templates.git
git fetch origin pull/17/head:pull_17
git checkout pull_17`

**Comment by ameerhamza6733** [comment] 2021-04-29 05:57
i am getting this error after pulling this #17 

`:layout/gnt_medium_template_view: Can't convert value at index 4 to dimension: type=0x4
     Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 4 to dimension: type=0x4
        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:788)
        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8336)
        at androidx.constraintlayout.widget.ConstraintLayout$LayoutParams.<init>(ConstraintLayout.java:2691)
        at androidx.constraintlayout.widget.ConstraintLayout.generateLayoutParams(ConstraintLayout.java:1916)
2021-04-29 10:48:39.969 30709-30709/com.ameerhamza6733.directmessagesaveandrepost E/AndroidRuntime:     at androidx.constraintlayout.widget.ConstraintLayout.generateLayoutParams(ConstraintLayout.java:482)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1146)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1105)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1147)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1105)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1147)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:660)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at com.google.android.ads.nativetemplates.TemplateView.initView(TemplateView.java:281)
        at com.google.android.ads.nativetemplates.TemplateView.<init>(TemplateView.java:63)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1014)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1144)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1105)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1147)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1105)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1147)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1105)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1147)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1105)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1147)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1105)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)`

**Comment by brokenheart2020** [comment] 2022-09-04 02:29
incompatible types: UnifiedNativeAd cannot be converted to NativeAd

**Comment by JillSong** [comment] 2023-11-06 16:19
Obsolete. UnifiedNativeAd was deprecated and deleted. Please update to the lastest GMA SDK.

**Closed by JillSong** 2023-11-06 16:19 UTC
